# Experiment
seed: 0
batch_size: 50
start: 0
num_images: 1000
rand: false

# Dataset
data_type: 'CIFAR10'

# Model
model_type: 'WideResNet'
train_type: 'adv_linf'

# Preemptive robustification
defense_type: 'PreemptRobustLinf'
delta: 0.03137
lr: 0.1
num_iters: 100
hessian: false

attack_type: 'PGDAttackLinf'
epsilon: 0.03137
step_size: 0.00784
num_steps: 20
random_starts: 1

# Evaluation
batch_size_eval: 50
attack_type_eval: 'PGDAttackLinf'
num_steps_eval: 20
bbox_epsilon: 0.03137 # for black-box attack 
wbox_epsilon_p: 0.03137 # for white-box attack, choose one from {0.00784, 0.01569, 0.02353, 0.03137}
wbox_epsilon: 0.03137 # for white-box attack
