# Experiment
seed: 0
batch_size: 50
start: 0
num_images: 1000
rand: true
scale: 0.1

# Dataset
data_type: 'CIFAR10'

# Model
model_type: 'WideResNet'
train_type: 'gaussian_0.1'

# Preemptive robustification
defense_type: 'PreemptRobustL2Rand'
delta: 0.5
lr: 0.005
num_iters: 100
hessian: false

attack_type: 'PGDAttackL2Rand'
epsilon: 0.5
step_size: 0.125
num_steps: 20
random_starts: 1
num_samples: 5

# Evaluation
batch_size_eval: 5
attack_type_eval: 'PGDAttackL2Rand'
num_steps_eval: 20
num_samples_eval: 50
bbox_epsilon: 0.5  # for black-box attack
wbox_epsilon_p: 0.5  # for white-box attack, choose one from {0.125, 0.25, 0.375, 0.5} 
wbox_epsilon: 0.5  # for white-bos attack
